name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PATH: keystore.jks
      APK_PATH: app/build/outputs/apk/release/app-release.apk
      RELEASE_NAME: "Release ${{ github.ref_name }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

      - name: Verify Java Home
        run: echo $JAVA_HOME

      - name: Decrypt Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > $KEYSTORE_PATH

      - name: Download dependencies
        run: ./gradlew build --stacktrace

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ env.RELEASE_NAME }}
          body: "Release of version ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload APK to GitHub Release
        id: upload-release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $APK_PATH
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
