name: Android CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PATH: keystore.jks
      APK_UNSIGNED_PATH: app/build/outputs/apk/release/app-release-unsigned.apk
      APK_SIGNED_PATH: app/build/outputs/apk/release/app-release.apk
      ANDROID_SDK_ROOT: $HOME/android-sdk

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Android SDK
        run: |
          mkdir -p $ANDROID_SDK_ROOT
          sudo chown $USER:$USER $ANDROID_SDK_ROOT
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "build-tools;30.0.3" "platforms;android-30"

      - name: Set up Android SDK path
        run: echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV

      - name: Decrypt Keystore
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > $KEYSTORE_PATH

      - name: Download dependencies
        run: ./gradlew build --stacktrace

      - name: Run tests
        run: ./gradlew test --stacktrace

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign APK
        run: |
          $ANDROID_SDK_ROOT/build-tools/30.0.3/apksigner sign --ks $KEYSTORE_PATH --ks-key-alias ${{ secrets.KEY_ALIAS }} \
          --ks-pass pass:${{ secrets.STORE_PASSWORD }} --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          --out $APK_SIGNED_PATH $APK_UNSIGNED_PATH

      - name: Verify APK Signature
        run: $ANDROID_SDK_ROOT/build-tools/30.0.3/apksigner verify $APK_SIGNED_PATH

      - name: Display project file tree
        run: |
          sudo apt-get install -y tree
          tree -L 2000

      - name: Check if APK exists
        run: ls -R $APK_SIGNED_PATH

  create_release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Release of version ${{ github.ref_name }}"
          draft: false
          prerelease: false

      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $APK_SIGNED_PATH
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
